version: '3'
services:
  ftr_visualization:
    build: .
    ports:
      - "80:5000"
    environment:
      - "MONGO_STRING="
    volumes:
      - "./flask_app:/etc/flask_app"
  redis:
    image: redis:alpine
    restart: always
