version: '3'
services:
  ftr_visualization:
    image: ghcr.io/1blattpapier/ftr-visualization:main
    ports:
      - "80:5000"
    environment:
      - "FLASK_APP=/etc/flask_app/app.py"
    volumes:
      - "./flask_app:/etc/flask_app"